### ISSUE TITLE
Fix Strings plugin

### ISSUE THREAD

**Issue by jseidl** [trendmicro/aleph#28]
Better handling of Unicode data, review regexes (URI, FILE etc)

**Comment by turicas** [comment]
As the file could be in any encoding (or actually a binary), the plugin should not try to decode the whole file, should it?
The way it works today (`f.read().decode('latin1').encode('utf8')`) can lead to many `UnicodeDecodeError` or `UnicodeEncodeError`s (unless you receive only `latin1`-encoded files).

**Comment by jseidl** [comment]
Makes sense. I've added those to try to fix an error I was having and
apparently I've created another problem, lol.

Gotta get back to this plugin to try to sort this out

**Comment by turicas** [comment]
You may use the 'ignore' flag on `.decode` so Python will ignore the bytes it can't decode using that codec. For example:
```python
>>> binary_data = '\x99...Álvaro...'  # contains '\x99' which is not valid UTF-8
>>> my_string = binary_data.decode('utf-8')
[...]
UnicodeDecodeError: 'utf8' codec can't decode byte 0x99 in position 0: invalid start byte
>>> my_string = binary_data.decode('utf-8', 'ignore')
>>> print my_string
...Álvaro...
```

So this is the best way to extract UTF-8 strings from any arbitrary (binary) data. The problem is: you need to try UTF-8 **and other codecs**, since the string could be encoded in a any of them. You may try the most common ones:

```python
binary_data = '...'  # set binary data here
codecs_to_try = ['utf-8', 'ascii', 'iso-8859-1']
strings = set(binary_data.decode(codec, 'ignore') for codec in codecs_to_try)
```

**Comment by jseidl** [comment]
That's a pretty cool solution also. I've ended up going simpler by getting only printable characters but I think we can have two modes (printable only or decoded). I'll push my mods and then you may add this option on top.

**Comment by jseidl** [comment]
Now someone needs to test but I think it's closed
