### ISSUE TITLE
Deploy a private demo instance (will be used for tests)

### ISSUE THREAD

**Issue by turicas** [trendmicro/aleph#37]
- [ ] Deploy the new version (maybe `0.1.1`)
- [ ] Add link to the website

**Comment by jseidl** [comment]
Web ui should be http Auth protected for now. It has no maturity so far to
be publicly available.

**Comment by merces** [comment]
You mean it must use SSL, right?

**Comment by jseidl** [comment]
I mean http Auth digest so only people with login and password can access.

And ssl of course.

When the ui gets stable we can open to public.

**Comment by merces** [comment]
Private demo is up and running.
