### ISSUE TITLE
Automatically create directories if needed

### ISSUE THREAD

**Issue by turicas** [trendmicro/aleph#39]
Verify if some `local` source at `SAMPLE_SOURCES` does not exists and create it automatically.

**Comment by igorrincon** [comment]
Working.... : )

**Comment by jseidl** [comment]
Be sure to check if aleph has sufficient rights for it

**Comment by jseidl** [comment]
I think this issue is closed https://github.com/trendmicro/aleph/blob/master/aleph/collectors/__init__.py#L13 

If not I'll reopen
