### ISSUE TITLE
Change link of ElasticSearch

### ISSUE THREAD

**Issue by igorrincon** [trendmicro/aleph#51]
Actually the link of ElasticSearch on Readme.md points to:

https://github.com/trendmicro/aleph/blob/master/www.elasticsearch.org

We have to change to:

www.elasticsearch.org

Igor Rincon

**Comment by igorrincon** [comment]
Better..

Change to: https://www.elastic.co/downloads/elasticsearch

Igor Rincon

**Comment by jseidl** [comment]
Better point to the main page so users can better understand what it is
instead of dropping on download page

**Comment by igorrincon** [comment]
Pointed. : )

**Comment by turicas** [comment]
This was fixed already on `development` branch (cd4deced5ace1e9c8992421182552e71998b410a).
