### ISSUE TITLE
Add python-pip on readme.md

### ISSUE THREAD

**Issue by igorrincon** [trendmicro/aleph#53]
Add python-pip on readme.md,  in:

## Requirements

In order to get a clean and nice install, you should download some requirements: Ubuntu/Debian

<code>apt-get install python-pyrex libffi-dev libfuzzy-dev python-dateutil libsqlite3-dev</code>

**Comment by merces** [comment]
Closed by (bf820ca4bd5e06f414138c378422abc311dd0d58), thanks!
