### ISSUE TITLE
Having problems to log in 

### ISSUE THREAD

**Issue by Pr0teus** [trendmicro/Aleph#64]
When installing Aleph some users may skip the step of creating a SECRET KEY into settings.py. And  creating the SQLlite database first, when this occurs users can't correctly login in the webinterface.

**Comment by jseidl** [comment]
This is expected since the secret key is used to salt the hash of the
passwords. This needs to be documented and the create db script should
check if the secret key is set.

**Comment by Pr0teus** [comment]
@jseidl yep, i'll commit the fix soon

**Comment by Pr0teus** [comment]
fixed at #65
